# Generated by Django 2.2.4 on 2021-10-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_travels', '0002_auto_20211006_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_travels', to='app_users.User'),
        ),
    ]
